---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huifer.
--- DateTime: 2020/12/10 13:16
---


local http = require("socket.http")
local ltn12 = require("ltn12")

httpUtils = {}

function http.put(u)
    local t = {
    }
    local r, c, h = http.request {
        url = u,
        sink = ltn12.sink.table(t),
        method = "PUT",
    }
    return r, c, h, table.concat(t)
end

function http.delete(u)
    local t = {
    }
    local r, c, h = http.request {
        url = u,
        sink = ltn12.sink.table(t),
        method = "DELETE",
    }
    return r, c, h, table.concat(t)
end

function http.get(u)
    local t = {
    }
    local r, c, h = http.request {
        url = u,
        sink = ltn12.sink.table(t) }
    return r, c, h, table.concat(t)
end

function http.post(u)
    local t = {
    }
    local r, c, h = http.request {
        url = u,
        sink = ltn12.sink.table(t),
        method = "POST",
    }
    return r, c, h, table.concat(t)
end

function httpUtils.wb_getUrl(url)
    local r, c, h, body = http.get(url)
    if c ~= 200 then
        print("ErrorCode: " .. c .. "ErrorMessage:" .. body)
        return
    else
        return body
    end
end

function httpUtils.wb_postUrl(url)
    local r, c, h, body = http.post(url)
    if c ~= 200 then
        print("ErrorCode: " .. c .. "ErrorMessage:" .. body)
        return
    else
        return body
    end
end

function httpUtils.wb_deleteUrl(url)
    local r, c, h, body = http.delete(url)
    if c ~= 200 then
        print("ErrorCode: " .. c .. "ErrorMessage:" .. body)
        return
    else
        return body
    end
end

function httpUtils.wb_putUrl(url)
    local r, c, h, body = http.put(url)
    if body ~= nil then
        return body
    end
    return body
end

return httpUtils

